---

# 创建虚拟机
# 用法: ap playbooks/create-vm.yaml
#       ap playbooks/create-vm.yaml -e "vm_name=ubuntu26-01"  # 只创建指定VM

- name: Create virtual machines
  gather_facts: false
  hosts: "{{ HOSTS | default('kvm_hosts') }}"
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: create_vm
      tags: create_vm
